const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const nodes=new Map();const $=id=>{if(!nodes.has(id))nodes.set(id,{value:'',textContent:'',innerHTML:'',disabled:false});return nodes.get(id);};
$('#composer-delivery').value='';$('#composer-target').value='';$('#composer-gpu').value='';$('#composer-need').value='识别目标';
const calls=[],steps=['qos_guarantee'];let pending=null;
let modelStatus={configured:true},statusError=null,statusPending=null;
const proposal={name:'目标检测套餐',description:'检测移动目标',steps:[{capability_id:'target_detection',params:{area:'A'}}]};
const ctx={console,$,$$:()=>[],window:{},wb:{epoch:1},pipeSteps:steps,CAPS:[{id:'target_detection',name:'目标检测'}],renderPipe(){},renderComposer:async()=>{},jfmt:JSON.stringify,esc:x=>String(x),apiKey:()=>true,wbMessage:e=>e.message,wbLoadNetwork:async()=>{},setTimeout:()=>1,clearTimeout(){},wbJob:async(b,t,f)=>f(ctx.wb.epoch),api:async(path,opts)=>{calls.push({path,body:opts&&JSON.parse(opts.body)});if(path.endsWith('/recommend')){if(pending)return pending;return {proposal,validation:{valid:true,warnings:[],errors:[]}};}if(path.endsWith('/validate'))return {valid:true,errors:[],warnings:[]};if(path.endsWith('/packages'))return {name:'已保存'};if(statusError)throw statusError;return statusPending||modelStatus;}};
vm.createContext(ctx);vm.runInContext(fs.readFileSync('static/composer.js','utf8'),ctx);
(async()=>{
 await $('#composer-recommend').onclick();
 assert.deepEqual(steps,['qos_guarantee'],'recommendation must not mutate draft');
 assert.equal(calls.length,1,'no save/publish/invoke before confirmation');
 assert.deepEqual(calls[0].body.context,{},'optional constraints must not be supplied by default');
 $('#composer-confirm').onclick();assert.deepEqual(steps,['target_detection']);
 assert.equal(calls.length,1,'adopting proposal is still only a draft');
 await $('#pipe-create').onclick();assert.equal(calls[1].path,'/api/v1/network/packages');
 assert.equal(calls[1].body.steps[0].params.area,'A');assert.deepEqual(steps,[]);
 $('#composer-delivery').value='batch';$('#composer-target').value='detection';$('#composer-gpu').value='40';
 assert.equal(JSON.stringify(ctx.composerContext()),JSON.stringify({delivery:'batch',target_source:'detection',gpu_budget_pct:40}));
 let finish;pending=new Promise(resolve=>finish=resolve);const request=$('#composer-recommend').onclick();ctx.wb.epoch++;ctx.window.wbComposerReset();finish({proposal,validation:{warnings:[]}});await request;
 assert.equal($('#composer-proposal').textContent,'','old account response must be discarded');
 pending=null;await $('#composer-recommend').onclick();$('#composer-gpu').value='40';$('#composer-gpu').onchange();
 $('#composer-confirm').onclick();assert.deepEqual(steps,[],'changed constraints invalidate proposal');
 modelStatus={configured:false,message:'服务进程未加载模型 API Key'};await ctx.renderComposer();
 assert.equal($('#composer-model-status').textContent,modelStatus.message);
 modelStatus={configured:true,message:'模型已配置'};await ctx.renderComposer();
 assert.equal($('#composer-model-status').textContent,'模型已配置');
 statusError=new Error('账号已失效');await ctx.renderComposer();
 assert.equal($('#composer-model-status').textContent,'状态查询失败：账号已失效');
 statusError=null;let finishStatus;statusPending=new Promise(resolve=>finishStatus=resolve);
 const statusRequest=ctx.renderComposer();await Promise.resolve();ctx.wb.epoch++;ctx.window.wbComposerReset();
 finishStatus({configured:true,message:'模型已配置'});await statusRequest;
 assert.equal($('#composer-model-status').textContent,'待连接','old status must not cross accounts');
 console.log('Composer confirmation, status diagnostics, request payload and stale-account guards passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
